googleapis/langchain-google-alloydb-pg-python

- src/langchain_google_alloydb_pg/alloydb_engine.py
In this commit we update the documentation for the ainit_document_table function. Previously the documentation said the argument metadata_columns was a list of SQLAlchemy columns. This is incorrect, as we have defined our own Column type.
> chore: update documentation for ainit_document_table function

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
- samples/langchain_quick_start.ipynb
> docs: update tutorials and add GitHub links

- samples/langchain_quick_start.ipynb
Fix version of vertex ai embeddings so that it uses 003 not just latest.
> docs: Update langchain_quick_start.ipynb

- README.md
case sensitivity causes this import not to resolve properly:
```
from langchain_google_alloydb_pg import AlloyDBEngine, AlloyDBVectorstore
ImportError: cannot import name 'AlloyDBVectorstore' from 'langchain_google_alloydb_pg' (/usr/local/lib/python3.12/site-packages/langchain_google_alloydb_pg/__init__.py). Did you mean: 'AlloyDBVectorStore'?
```
> Correcting vectorstore import

- src/langchain_google_alloydb_pg/alloydb_engine.py
No longer need to convert the `ip_type` to the Python Connector enum.
I added native support for `ip_type` as `str` to the AlloyDB Python Connector. Now the converting can be offloaded and not required here in the langchain package.
Ref: https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/267
P.S: This will also add PSC support for free once the Python Connector version is bumped to 1.1.0 which has PSC support (released today).
> chore: remove `ip_type` conversion

- .github/CODEOWNERS
- .github/sync-repo-settings.yaml
1. set langchain-alloydb github team as owner
2. give it `push` permission
> chore: Set up github teams ownership and permission

- pyproject.toml
- requirements.txt
This library uses only async SQLAlchemy connection pool engines. Thus, it should be depending on `sqlalchemy[asyncio]` and not regular sqlalchemy.
This will fix required deps on macOS: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1
Fixes #115
> fix: update required dependencies to use SQLAlchemy[asyncio]

- src/langchain_google_alloydb_pg/alloydb_engine.py
As pointed out in #110 there is no point of calling the Google OAuth2 endpoint if we already have the service account field tied to the credentials... unless I'm missing something. 
https://github.com/googleapis/langchain-google-alloydb-pg-python/blob/9ce7a4bc4257d7e0fe90c1bab1740326b4c7d12f/src/langchain_google_alloydb_pg/alloydb_engine.py#L62-L75
We should be returning early and skipping the overhead of the API call if we already know the IAM principal based on the credentials attribute. This is what we do already in the [Cloud SQL MySQL package](https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/blob/main/src/langchain_google_cloud_sql_mysql/engine.py#L73).
> refactor: return early if credentials have service account field

- .coveragerc
- DEVELOPER.md
- integration.cloudbuild.yaml
- pyproject.toml
Add code coverage check as part of running test suite. Test suite will fail with coverage below the current level 83% (target 90%).
> ci: Add code coverage check

- pyproject.toml
- src/langchain_google_alloydb_pg/alloydb_chat_message_history.py
- src/langchain_google_alloydb_pg/alloydb_engine.py
- src/langchain_google_alloydb_pg/alloydb_loader.py
- src/langchain_google_alloydb_pg/alloydb_vectorstore.py
- src/langchain_google_alloydb_pg/indexes.py
Disallow incomplete or missing function types
> ci: Add mypy function type check 

- .coveragerc
Code coverage threshold was arbitrarily put at 84%.
Python versions 3.8, 3.9 and 3.10 have coverage at 83.5% which 
is causing flaky builds.
Setting to 82% for now and additional coverage will be a fast follow.
> ci: change code coverage threshold

- pyproject.toml
- requirements.txt
- src/langchain_google_alloydb_pg/alloydb_engine.py
The AlloyDB Python Connector just released a new version `v1.2.0`
that supports setting the `refresh_strategy` argument of the connector.
Setting the refresh strategy to lazy refresh is recommended for
serverless environments. As the default refresh strategy is to
have background refreshes occur to get the instance metadata and a fresh
certificate to use for the SSL/TLS connection. 
However, these background refreshes can be throttled when serverless 
environments scale to zero (Cloud Functions, Cloud Run etc.).
This PR will fix the ambiguous errors that are a result of the CPU being
throttled for the AlloyDB Connector.
Fixes #160
> fix: use lazy refresh for AlloyDB Connector

- src/langchain_google_alloydb_pg/indexes.py
`pgvector` has IVFFlat `lists` parameter default to `100`(https://github.com/pgvector/pgvector/blob/d1694a93afe4d23d0bc3ca6f9c85f06fb79a325c/src/ivfflat.h#L42) but our implementation defaults to `1`. We should change the default to match the `pgvector` setting.
> fix: Change IVFFlat `lists` default to 100

- README.rst
- src/langchain_google_alloydb_pg/engine.py
Add `key` object to engine constructor to prevent constructor usage.
> fix: Add `key` to engine constructor

- src/langchain_google_alloydb_pg/indexes.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_alloydb_vectorstore_index.py
Add table name as prefix to default index name upon index creation to avoid conflicting default index names for different tables.
1. Change `DEFAULT_INDEX_NAME` to `DEFAULT_INDEX_NAME_SUFFIX`.
2. Change `index_name` default in the `BaseIndex` class to `None`.
3. In `aapply_vector_index()`, check if the `index_name` field is `None` and if so, give it a default index name (`table_name` + `DEFAULT_INDEX_NAME_SUFFIX`).
> feat: Add table name to default index name

- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_alloydb_vectorstore_search.py
Implements LangChain `_select_relevance_score_fn` function to support similarity search with score threshold: https://github.com/langchain-ai/langchain/blob/cb95198398a66737f1a7f7e0f63417802e03190c/libs/core/langchain_core/vectorstores/base.py#L611
btw fix a titel size in README.rst
> feat: Add similarity search score threshold select function

- src/langchain_google_alloydb_pg/loader.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_alloydb_vectorstore.py
If the user doesn't provide IDs when adding vector store embeddings, auto-generate integer IDs for them.
> feat: Auto-generate IDs upon adding embeddings

- samples/index_tuning_sample/index_search.py
- src/langchain_google_alloydb_pg/chat_message_history.py
- src/langchain_google_alloydb_pg/engine.py
- src/langchain_google_alloydb_pg/indexes.py
- src/langchain_google_alloydb_pg/loader.py
- src/langchain_google_alloydb_pg/vectorstore.py
> docs: Add docstring to all methods

- src/langchain_google_alloydb_pg/indexes.py
pgvector reference for vector functions: https://github.com/pgvector/pgvector?tab=readme-ov-file#vector-functions
> fix: Rename inner product distance search function to `inner_product`

- src/langchain_google_alloydb_pg/vectorstore.py
The create functions in the AlloyDB vector store raise an error when provided with a non-existent table name. 
To create a new table before initializing a vector store, use the init_vectorstore_table function in the engine.
> docs: create functions need pre-existing tables

- docs/how_to_choose_an_index_guide.md
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_alloydb_vectorstore_index.py
Breaking change!
Rename of `postgres_ann` extension (Current available on AlloyDB Omni GA and  available on AlloyDB Cloud as a private preview) to `alloydb_ann`. If using with Omni, update to the latest version of AlloyDB Omni use correctly.
> fix!: Update `postgres_ann` to `alloydb_scann`

- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/engine.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_async_vectorstore_from_methods.py
- tests/test_engine.py
- tests/test_vectorstore_from_methods.py
feat: allow non-uuid data types for vectorstore primary key
> feat: allow non-uuid data types for vectorstore primary key

- pyproject.toml
- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_async_vectorstore.py
- tests/test_async_vectorstore_search.py
- tests/test_vectorstore.py
- tests/test_vectorstore_search.py
1. Add new image search APIs `similarity_search_image()` and `asimilarity_search_image()`.
2. Add `add_images()` and `aadd_images()` endpoints to add images to vector store.
3. Add tests.
> feat: Add multi-modal support vector store

- .github/sync-repo-settings.yaml
- DEVELOPER.md
- README.rst
- integration.cloudbuild.yaml
- pyproject.toml
- requirements.txt
Langchain v0.3 remove support for py3.8. Py3.8 within the year will be EOL; therefore removing support from future versions
> feat: remove support for Python 3.8

- pyproject.toml
- requirements.txt
- src/langchain_google_alloydb_pg/async_vectorstore.py
- tests/test_async_vectorstore.py
- tests/test_async_vectorstore_search.py
- tests/test_vectorstore.py
- tests/test_vectorstore_search.py
1. Add GCS and web URI support for image embedding (for VertexAIEmbedding use only. Other embedding models mostly only support local URI).
2. Update embedding service's image embedding API call to check for both `embed_images()` and `embed_image()` methods to accommodate different interfaces.
> feat: Add GCS URI support for image embedding

- .github/workflows/cloud_build_failure_reporter.yml
The reporter should comment on issues related to the test.
See manual testing result: https://github.com/duwenxin99/test-alloydb-lc/issues
> fix: Cloud Build reporter issue comment

- samples/langchain_on_vertexai/requirements.txt
Reasoning engine is failing in https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/283 hence this PR is needed to fix the tests.
Without this change, the tests in reasoning engine fail: [test log](https://pantheon.corp.google.com/cloud-build/builds;region=global/fcf59fc2-f3bd-40f8-b40e-226b9323f22f;step=2?e=13802955&inv=1&invt=Abjoqw&mods=logs_tg_staging&project=langchain-alloydb-testing) saying:
`NameError: name 'SafetySetting' is not defined. Did you mean: 'SafetySettingsType'?`
which is caused due to below exception:
```
File "/builder/home/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1229, in _common_field_schema
raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name …
```
> chore: pin pydantic version to avoid a reasoning engine failure

- samples/index_tuning_sample/README.md
- samples/langchain_on_vertexai/prebuilt_langchain_agent_template.py
- samples/langchain_on_vertexai/requirements.txt
- src/langchain_google_alloydb_pg/async_chat_message_history.py
- src/langchain_google_alloydb_pg/async_loader.py
- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/chat_message_history.py
- src/langchain_google_alloydb_pg/embeddings.py
- src/langchain_google_alloydb_pg/engine.py
- src/langchain_google_alloydb_pg/indexes.py
- src/langchain_google_alloydb_pg/loader.py
- src/langchain_google_alloydb_pg/model_manager.py
- src/langchain_google_alloydb_pg/utils/pgvector_migrator.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_async_vectorstore.py
- tests/test_async_vectorstore_search.py
- tests/test_chatmessagehistory.py
- tests/test_vectorstore.py
- tests/test_vectorstore_search.py
- tests/util_tests/test_pgvector_migrator.py
As of Python 3.9 and [PEP 585](https://peps.python.org/pep-0585/#implementation) we can use standard collections like
`list`, `dict`, `tuple` for typing instead of the  now deprecated
```python
from typing import Dict, List, Tuple ...
```
Also removing a ton of unused imports.
Pinned `pydantic` package version to 2.9.0 to avoid a reasoning engine failure.
> chore: adhere to PEP 585 and removed unused imports

- src/langchain_google_alloydb_pg/model_manager.py
- tests/test_model_manager.py
> fix: update MEM version comparison

- README.rst
- samples/index_tuning_sample/README.md
- samples/migrations/migrate_pgvector_to_alloydb.md
- samples/migrations/migrate_vectorstore_to_alloydb.md
- Updated Readme to have sync to async conversion
- Updated copy/paste tutorials to sync
> docs: update docs to convert sync to async

- src/langchain_google_alloydb_pg/engine.py
- tests/test_engine.py
Adds an "engine_args" argument to engine creation functions that can be used to specify additional parameters to the underlying pool creation.
> feat: add engine_args argument to engine creation functions

- tests/test_async_vectorstore_index.py
- tests/test_vectorstore_index.py
Adding delete index statements to avoid `DuplicateTableError: Index already exists` errors.
Adding these as part of auditing the other repos across LC & LI, for alloy db & Cloud sql
> chore: add drop index statements to avoid conflict

- samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
- samples/migrations/migrate_milvus_vectorstore_to_alloydb.py
- samples/migrations/migrate_qdrant_vectorstore_to_alloydb.py
- samples/migrations/migrate_weaviate_vectorstore_to_alloydb.py
- samples/migrations/requirements.txt
- samples/migrations/test_milvus_migration.py
- samples/migrations/test_pinecone_migration.py
- samples/migrations/test_qdrant_migration.py
- samples/migrations/test_weaviate_migration.py
<details>
<summary>PyTest log</summary>
`cd samples/migrations`
```
(venv311) (base) ➜  migrations git:(code-snippets-weaviate) ✗ venv311/bin/pytest -v test_weaviate_migration.py
/usr/local/google/home/vishwarajanand/github/langchain-google-alloydb-pg-python/samples/migrations/venv311/lib/python3.11/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", …
```
> chore: fix weaviate snippets

- src/langchain_google_alloydb_pg/chat_message_history.py
- tests/test_chatmessagehistory.py
Unblocks lint failures in https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/339
[Lint workflow](https://github.com/googleapis/langchain-google-alloydb-pg-python/actions/runs/13153274803/job/36770910902?pr=339) is complaining:
```
src/langchain_google_alloydb_pg/chat_message_history.py:111: error: Cannot override writeable attribute with read-only property  [override]
```
This happens because we are only defining `@property` but not `@messages.setter` since the base class `BaseChatMessageHistory` defines `messages` as a writeable prop.
Adding definition and relevant test.
> Note: this failure is only reported with latest `mypy==1.15.0` version.
> fix: add write messages to Chat History

- src/langchain_google_alloydb_pg/async_vectorstore.py
chore: Enquote column names to not match reserved keywords.
> fix: Enquote column names to not match reserved keywords.

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
Pinecone's `fetch` expects a namespace when a custom namespace is used.
> chore(samples): update samples to fix pinecone data fetch with non-default namespace

- src/langchain_google_alloydb_pg/vectorstore.py
A bug was identified in the `asimilarity_search_image()` function in the `vectorstore.py` file. The function incorrectly calls `asimilarity_search()` instead of `asimilarity_search_image()`, causing image search functionality to fail.
```python
async def asimilarity_search_image(self, image_uri, k=4, filter=None, **kwargs):
"""Return docs selected by similarity search on query."""
return await self._engine._run_as_async(
self.__vs.asimilarity_search(image_uri, k, filter, **kwargs)
)
```
```python
async def asimilarity_search_image(self, image_uri, k=4, filter=None, **kwargs):
"""Return docs selected by similarity search on image_uri."""
return await self._engine._run_as_async(
self.__vs.asimilarity_search_image(image_uri, k, filter, **kwargs)
)
```
This bug prevents image-based similarity …
> fix(asimilarity_search_image): fix bug in image search functionality

- pyproject.toml
- requirements.txt
Reverts googleapis/langchain-google-alloydb-pg-python#334
We can continue to support the larger range for the GCS dependency and test against the newest versions via requirements.txt.
> fix: Revert "chore(deps): update dependency google-cloud-storage to v3"

- src/langchain_google_alloydb_pg/async_vectorstore.py
- tests/test_async_vectorstore_search.py
- tests/test_standard_test_suite.py
- tests/test_vectorstore_embeddings.py
- tests/test_vectorstore_search.py
chore: support ids in Documents and update insert SQL query to upsert
fixes [b/376065787](https://b.corp.google.com/issues/376065787)
> chore: support ids in Documents and update insert SQL query to upsert

- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_async_vectorstore_search.py
chore: Minor cleanup of vectorstore 
All the review comments from the [cloud sql pr](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/276) are being propogated here
> chore: Minor cleanup of vectorstore

- samples.cloudbuild.yaml
- samples/migrations/requirements.txt
- samples/migrations/test_pinecone_migration.py
- samples/migrations/tests.cloudbuild.yaml
[b/388979186](http://b/388979186)
> tests: add db migration guide sample tests 

- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/utils/pgvector_migrator.py
- tests/test_engine.py
- tests/util_tests/test_pgvector_migrator.py
Per [this comment](https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/327#issuecomment-2685689004), separating out the code changes for numpy #V2.
This change is needed because when using numpy V2, if a numpy array is converted to string then it comes as numpy objects rather than float array. [ref](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/247#issuecomment-2652914015)
1. Parsing embedding dimensions individually for accommodating numpy V2 values.
- Includes fixes for `utils/pgvector_migrator.py`
3. Updating tests accordingly.
> refactor: parse embedding dimensions as float[] for numpyV2

- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/indexes.py
- tests/test_indexes.py
- tests/test_vectorstore_index.py
chore: Prepare package for upstreaming langchain changes
For bug - [b/401013845](https://b.corp.google.com/issues/401013845)
This PR prepares the package for upstreaming changes to langchain-postgres.
The changes are restricted to vectorstore.
- Instead of checking for `ScaNNIndex` class instance while applying a vector index, the integration now relies on the use to specify if the `ScaNNIndex` extension needs to be created .
- Removes the check for AlloyDBEmbeddings and checks if the provided embedding class has the function `embed_query_inline`
These changes are made so as to not have a circular import on upstreaming these changes to langchain-postgres
> chore: Prepare package for upstreaming langchain changes

- requirements.txt
The new version of connectors for Alloy DB are leading to test failures, ref tests in https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/381.
This PR pins the issue to connector's latest version so that other packages can be unblocked from version updates.
> chore(deps): update connectors

- samples/migrations/tests.cloudbuild.yaml
https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/381 is seeing failures while trying to execute samples in GCB, [ref test log](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/37bf8bc7-e404-4f0e-99ee-f53b1f8f329d;step=1?e=13802955&mods=logs_tg_staging&project=langchain-alloydb-testing).
The reason is that `langgraph-checkpoint` package is missing, despite being added in root `requirements.txt`. In order to fix such issues even in future, adding pip installs of all base packages while running samples too.
1. The cloud build might not catch if a source dependency is required by our package to run samples, because we anyway install them. An alternate solution is to add `langgraph-checkpoint` (or any other package dependency) added to root to the …
> tests: fix the missing dependencies for samples gcb

- tests/test_async_checkpoint.py
- tests/test_checkpoint.py
Lint seems to be failing for checkpointer tests, [ref test log](https://github.com/googleapis/langchain-google-alloydb-pg-python/actions/runs/14622579181/job/41026159411?pr=381) in another PR: https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/381
Reviewer point:
1. Added comments for code suggestions. If `connectors.close` is not needed, reject the suggestions. Else, add them to a commit during review.
> chore(lint): fix lint in async checkpointer tests

- .github/renovate.json5
This PR intends to force the renovate bot PRs to not mixup the dependency upgrade in `samples` folder with others.
**Change:** A new package rule is added which would make the renovate bot do a separate PRs for `samples` folder and all dependency upgrades which go in that folder including, `samples/**requirements.txt`, .
1. Is `ignorePaths` [ref](https://docs.renovatebot.com/configuration-options/#ignorepaths) the correct tag, other promising contenders are `matchFileNames` (using a regex with a negation caret ^), `includePaths`
2. The above are not [packageRules](https://docs.renovatebot.com/configuration-options/#packagerules), there's no way to know. Should we use `matchPackageNames` instead (using a regex with a negation caret ^)?
<details>
<summary> 
<h3>Log for validating renovate …
> chore: separate renovate bot PRs for samples and non-samples

- tests/test_embeddings.py
- tests/test_model_manager.py
- tests/test_vectorstore_embeddings.py
Upgrade embedding models and associated scores in tests.
Since, latest models are not pre-registered, adding a call to specifically call `CREATE_MODEL` endpoint.
> tests: upgrade embedding model in tests

- src/langchain_google_alloydb_pg/async_vectorstore.py
- tests/test_async_vectorstore.py
fix: Add support for a metadata column named id
Fixes an issue that prevented adding a metadata column named `id` to the vector store, due to a conflict with the id parameter in the insert query. Users can now successfully include a metadata field with the name id.
> fix: Add support for a metadata column named id
