googleapis/langchain-google-alloydb-pg-python

- integration.cloudbuild.yaml
- pyproject.toml
- src/langchain_google_alloydb_pg/__init__.py
- src/langchain_google_alloydb_pg/alloydb_engine.py
- tests/test_alloydb_engine.py
> feat: add AlloyDBEngine

- integration.cloudbuild.yaml
- src/langchain_google_alloydb_pg/alloydb_engine.py
- tests/test_alloydb_engine.py
> feat: add user password auth

- src/langchain_google_alloydb_pg/__init__.py
- src/langchain_google_alloydb_pg/alloydb_engine.py
- src/langchain_google_alloydb_pg/alloydb_vectorstore.py
- src/langchain_google_alloydb_pg/indexes.py
- tests/test_alloydb_engine.py
- tests/test_alloydb_vectorstore.py
- tests/test_alloydb_vectorstore_from_methods.py
- tests/test_alloydb_vectorstore_index.py
- tests/test_alloydb_vectorstore_search.py
> feat: add alloydb vectorstore

- docs/chat_message_history.ipynb
- src/langchain_google_alloydb_pg/__init__.py
- src/langchain_google_alloydb_pg/alloydb_chat_message_history.py
- src/langchain_google_alloydb_pg/alloydb_engine.py
Changes Done
- Added the AlloyDBChatMessageHistory
- Added add_message, clear methods
- Added messages property
To be done
- Integration tests
- Documentation
> feat: add AlloyDB chatmessagehistory 

- src/langchain_google_alloydb_pg/__init__.py
- src/langchain_google_alloydb_pg/alloydb_engine.py
- src/langchain_google_alloydb_pg/version.py
> chore: add useragent to engine

- src/langchain_google_alloydb_pg/alloydb_engine.py
- src/langchain_google_alloydb_pg/alloydb_vectorstore.py
> chore: fix names

- pyproject.toml
- src/langchain_google_alloydb_pg/alloydb_vectorstore.py
> chore: remove dep on langchain-community

- docs/vector_store.ipynb
> docs: add Vectorstore docs

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- tests/test_alloydb_chatmessagehistory.py
> docs: add Document Loader docs

- docs/chat_message_history.ipynb
- docs/vector_store.ipynb
- src/langchain_google_alloydb_pg/alloydb_engine.py
- tests/test_alloydb_chatmessagehistory.py
- tests/test_alloydb_engine.py
- tests/test_alloydb_vectorstore.py
- tests/test_alloydb_vectorstore_from_methods.py
- tests/test_alloydb_vectorstore_index.py
- tests/test_alloydb_vectorstore_search.py
> feat: add sync methods

- docs/document_loader.ipynb
- src/langchain_google_alloydb_pg/alloydb_loader.py
- tests/test_alloydb_loader.py
> feat: add create methods for Loader

- src/langchain_google_alloydb_pg/alloydb_engine.py
- tests/test_alloydb_engine.py
> feat(engine): add from_engine method

- src/langchain_google_alloydb_pg/alloydb_chat_message_history.py
- src/langchain_google_alloydb_pg/alloydb_engine.py
- src/langchain_google_alloydb_pg/alloydb_loader.py
- src/langchain_google_alloydb_pg/alloydb_vectorstore.py
- tests/test_alloydb_loader.py
> feat: make run as sync private

- src/langchain_google_alloydb_pg/alloydb_engine.py
- src/langchain_google_alloydb_pg/alloydb_loader.py
- tests/test_alloydb_loader.py
> feat: add verify schema to saver

- src/langchain_google_alloydb_pg/alloydb_loader.py
> chore: fix typo

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
- src/langchain_google_alloydb_pg/alloydb_engine.py
`AlloyDBEngine.from_instance` should have region before cluster for proper positional arguments that match async implementation.
> fix: update `from_instance` arg order

- README.md
Update README to showcase working usage.
> chore: update README examples

- samples/langchain_quick_start.ipynb
In this commit we add a placeholder for the quickstart guide.
> docs: Add quickstart placeholder

- README.md
> chore: fix links in readme

- samples/langchain_quick_start.ipynb
In this commit we add in a demo langchain application for AlloyDB. We create an application utilizing all three integrations 1) The Document Loader 2) The Vector Store and 3) The Chat Message History.
> docs: Add Demo Langchain Application.

- .github/workflows/lint.yml
- .github/workflows/lint_fallback.yml
> chore(ci): add fallback lint

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
> docs: fix doc links

- samples/langchain_quick_start.ipynb
Update installs, need to add back in the alloydb-connector, it go axed somehow.
> docs: Update langchain_quick_start.ipynb

- .github/renovate.json5
> chore: test removing schedule from renovate

- src/langchain_google_alloydb_pg/alloydb_engine.py
- tests/test_alloydb_engine.py
> fix: sql statement for non-nullable columns

- renovate.json5
> chore: Update renovate.json5

- pyproject.toml
> chore: add python constraints to pyproject.toml

- pyproject.toml
> chore: Update README in pyproject.toml

- .kokoro/publish-docs.sh
> chore: Update publish-docs.sh

- .kokoro/publish-docs.sh
add pip3 install . and fix distribution
> docs: fix publish-docs.sh

- README.rst
Fix typo in code sample for "Vector Store Usage"
> chore(README.rst): fix typo in code sample for "Vector Store Usage"

- .github/blunderbuss.yml
- .github/header-checker-lint.yml
- DEVELOPER.md
1. Add blunderbuss config to auto-assign issues.
2. Fix some typos in DEVELOPER.md.
> ci: Add blunderbuss config

- DEVELOPER.md
- docs/vector_store.ipynb
- integration.cloudbuild.yaml
- src/langchain_google_alloydb_pg/alloydb_vectorstore.py
- src/langchain_google_alloydb_pg/indexes.py
- tests/test_alloydb_vectorstore.py
- tests/test_alloydb_vectorstore_index.py
Added 2 indexes:
1. IVF from pgvector++
2. SCANN from postgres_ann
Design Doc: https://docs.google.com/document/d/1w_-1Q8hdEEPyzoTmS6sruLmpYlSQPMWfUy5Ds4tIXIU/edit?tab=t.0#heading=h.i007da7g9lwp
> feat: Add IVF and ScaNN Indexes

- .github/header-checker-lint.yml
- .github/workflows/lint.yml
- .github/workflows/lint_fallback.yml
- samples/index_tuning_sample/README.md
- samples/index_tuning_sample/create_vector_embeddings.py
- samples/index_tuning_sample/index_search.py
- samples/index_tuning_sample/requirements.txt
Add index tuning guide and sample code
> doc: Add Index Tuning Guide and Samples

- src/langchain_google_alloydb_pg/engine.py
Adds documentation to some methods for clarity.
* ainit_document_table
* ainit_vectorstore_table
> chore: improving doc blocks

- .github/workflows/lint.yml
- src/langchain_google_alloydb_pg/engine.py
> chore(ci): remove pull_request_target

- src/langchain_google_alloydb_pg/loader.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_alloydb_engine.py
- tests/test_alloydb_loader.py
- tests/test_alloydb_vectorstore.py
- tests/test_alloydb_vectorstore_search.py
Add tests to reach 90% coverage
> feat: Add tests to reach 90% coverage

- src/langchain_google_alloydb_pg/indexes.py
Add ScaNN database flags as query options:
scann.num_leaves_to_search: int = 1
scann.pre_reordering_num_neighbors: int = -1
> feat: Add ScaNN index query options

- docs/how_to_choose_an_index_guide.md
- docs/index.rst
> docs: rename index guide

- src/langchain_google_alloydb_pg/indexes.py
> chore: release 0.6.0

- src/langchain_google_alloydb_pg/chat_message_history.py
- src/langchain_google_alloydb_pg/engine.py
- src/langchain_google_alloydb_pg/loader.py
- src/langchain_google_alloydb_pg/vectorstore.py
> feat: Add support for custom schema names

- src/langchain_google_alloydb_pg/engine.py
- src/langchain_google_alloydb_pg/loader.py
- src/langchain_google_alloydb_pg/vectorstore.py
> fix: Fix documentation comments for library methods.

- DEVELOPER.md
> chore(docs): Update DEVELOPER.md

- samples/README.md
Added docs to itemise code samples present in the repo.
> docs: Itemise code samples

- pyproject.toml
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_alloydb_vectorstore.py
fix: replacing cosine_similarity and maximal_marginal_relevance methods
> fix: replacing cosine_similarity and maximal_marginal_relevance methods

- samples/langchain_on_vertexai/README.md
> chore: release 0.7.0

- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_async_vectorstore.py
- tests/test_vectorstore.py
Tested Pinecone DB migration using this method: https://github.com/twishabansal/vector-store-experiments/blob/c6f264558c6dba38170000244dd85375a7e5c329/pinecone/app.py#L164
> feat: Made add_embeddings method public

- samples/migrations/vectorstore_to_alloy_db.md
Sample code to help users migrate their data from other VectorStores to AlloyDB.
> docs: Migration samples

- .kokoro/release.sh
- .kokoro/release/common.cfg
> chore(ci): fix kokoro release secret

- samples/README.md
- samples/migrations/migrate_vectorstore_to_alloydb.md
> chore(docs): update migration doc filename and readme

- samples/langchain_on_vertexai/README.md
> chore(docs): fix typo in samples readme

- samples/index_tuning_sample/create_vector_embeddings.py
- samples/index_tuning_sample/index_search.py
- samples/langchain_on_vertexai/clean_up.py
- samples/langchain_on_vertexai/create_embeddings.py
- samples/langchain_on_vertexai/requirements.txt
> chore(samples): update samples for async/sync refactor

- docs/vector_store.ipynb
Add multi-modal example to colab
> doc: Add multi-modal documentation

- docs/model_endpoint_management.ipynb
Adding documentation for Model Endpoint Management
> doc: adding documentation for Model Endpoint Management

- .kokoro/release.sh
- .kokoro/release/common.cfg
> chore(ci): update kokoro secret

- README.rst
> chore(docs): Update README with improvements

- samples/migrations/migrate_vectorstore_to_alloydb.md
Update migration guide to:
1. Separate out AlloyDB setup steps.
2. Mention the default use of Public IP.
Fixes [b/383570573](https://b.corp.google.com/issues/383570573) 🦕
> chore: Migration guide update

- samples/migrations/migrate_vectorstore_to_alloydb.md
> chore(docs): add context to vector store migration

- samples/migrations/migrate_vectorstore_to_alloydb.md
fix: Add multiple namespaces option in migration guide.
> fix: Add multiple namespaces option in migration guide.

- .github/workflows/docs.yml
> chore(ci): Update python version for docs pipeline

- docs/chat_message_history.ipynb
> chore(docs): update chat model

- pyproject.toml
- requirements.txt
- samples/index_tuning_sample/requirements.txt
- samples/requirements.txt
- tests/test_vectorstore.py
> chore: update package deps

- docs/document_loader.ipynb
docs: Reorder markdown in Document Loader Notebook
> docs: Reorder markdown in Document Loader Notebook

- requirements.txt
- src/langchain_google_alloydb_pg/async_checkpoint.py
- tests/test_async_checkpoint.py
Change Log:
[ ] Create AsyncAlloyDBSaver class
[ ] Create async put method
[ ] Create test for class and method
> feat(langgraph-base): create checkpoint aput method + tests

- requirements.txt
- src/langchain_google_alloydb_pg/async_checkpoint.py
- src/langchain_google_alloydb_pg/engine.py
- tests/test_async_checkpoint.py
- tests/test_engine.py
Change Log:
[ ] Create async put_writes method
[ ] Create test for method
> feat(langgraph-base): create async put_writes method + tests

- .github/workflows/cloud_build_failure_reporter.yml
- .github/workflows/docs.yml
[b/393704340](http://b/393704340)
> chore: update gh workflow permissions

- requirements.txt
- src/langchain_google_alloydb_pg/async_checkpoint.py
- tests/test_async_checkpoint.py
Change Log:
[ ] Create async put_writes method
[ ] Create test for method
> feat(Langgraph-base-alist): create async list method + tests

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/model_endpoint_management.ipynb
- docs/vector_store.ipynb
- samples/langchain_quick_start.ipynb
- samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
- samples/migrations/migrate_milvus_vectorstore_to_alloydb.py
- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
- samples/migrations/migrate_qdrant_vectorstore_to_alloydb.py
- samples/migrations/migrate_weaviate_vectorstore_to_alloydb.py
- samples/migrations/test_chromadb_migration.py
- samples/migrations/test_milvus_migration.py
- samples/migrations/test_pinecone_migration.py
- samples/migrations/test_qdrant_migration.py
- samples/migrations/test_weaviate_migration.py
chore: Highlight how to use Private IP in Engine class.
Fixes [b/396147892](https://b.corp.google.com/issues/396147892)
> chore: Highlight how to use Private IP in Engine class.

- pyproject.toml
- tests/test_standard_test_suite.py
Adding Langchain standard test suite for vectorstore for edge cases.
Fixes [b/375659546](https://b.corp.google.com/issues/375659546)
> chore: Add Langchain standard vectorstore tests.

- src/langchain_google_alloydb_pg/async_vectorstore.py
- src/langchain_google_alloydb_pg/vectorstore.py
- tests/test_async_vectorstore_search.py
- tests/test_vectorstore_search.py
feat: Add get_by_ids and aget_by_ids to vectorstore
Fixes [b/376065747](https://b.corp.google.com/issues/376065747)
> feat: Add get_by_ids and aget_by_ids to vectorstore

- samples/migrations/migrate_chromadb_vectorstore_to_alloydb.py
- samples/migrations/migrate_milvus_vectorstore_to_alloydb.py
- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
- samples/migrations/migrate_qdrant_vectorstore_to_alloydb.py
- samples/migrations/migrate_weaviate_vectorstore_to_alloydb.py
[b/6615186](http://b/6615186)
Added clarification notes to migration docs
> chore: add notes to migration docs

- .github/workflows/cloud_build_failure_reporter.yml
- .github/workflows/schedule_reporter.yml
chore: Update GHA workflow permissions for Cloud Build Reporter
> chore: Update GHA workflow permissions for Cloud Build Reporter

- README.rst
- docs/langgraph_checkpoint.ipynb
> docs(langgraph-base): Create documentation for LangGraph Checkpoint

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
> docs: Add comment for private IP support.

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
Add optional line to overwrite existing vector store to enable easier iteration.
Fixes #378  🦕
> docs: Add optional line to overwrite existing vector store

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
> docs: Add namespace parameter to inner loop of get_ids_batch()

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
> docs: fix pagination logic.

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
> docs: Add uuid generation.

- samples/migrations/migrate_pinecone_vectorstore_to_alloydb.py
> docs: Support non-uuid id column in vector store table.

- noxfile.py
- pyproject.toml
- requirements.txt
- src/langchain_google_alloydb_pg/__init__.py
- src/langchain_google_alloydb_pg/async_checkpoint.py
- src/langchain_google_alloydb_pg/checkpoint.py
- src/langchain_google_alloydb_pg/engine.py
- tests/test_async_checkpoint.py
- tests/test_checkpoint.py
- tests/test_engine.py
> feat(langgraph): add checkpointer interface

- README.rst
- docs/langgraph_checkpoint.ipynb
> docs(langgraph): add checkpointer docs

- src/langchain_google_alloydb_pg/engine.py
> fix(engine): loop error on close

- src/langchain_google_alloydb_pg/async_checkpoint.py
fix: Update JSON conversion method
Copying over fix from https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/296
> fix: Update JSON conversion method

- samples/langchain_on_vertexai/prebuilt_langchain_agent_template.py
- samples/langchain_on_vertexai/retriever_agent_with_history_template.py
- samples/langchain_on_vertexai/retriever_chain_template.py
Upgrading model to address failures in https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/381
> chore: model upgrade in samples

- pyproject.toml
- requirements.txt
- tests/test_async_checkpoint.py
chore: Upgrade langgraph dependency
This is to fix the failing nightly tests
> chore: Upgrade langgraph dependency
